// 试题
exports.questionList = {
  errcode: 200,
  errmsg: "操作成功",
  data:[
    {
      ctime: "2020-06-08 19:45:56",
      id: "277",
      memo: "",
      must: true,
      optionDTOS: [
        {
          checked: false,
          choices: "1",
          content: "A、订本账、活页账、卡片账 ",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "565",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: ""
        },
        {
          checked: false,
          choices: "2",
          content: "B、总分类账、明细分类账、日记账",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "566",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: ""
        },
        {
          checked: false,
          choices: "3",
          content: "C、序时账、分类账、日记账",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "567",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: "",
        },
        {
          checked: false,
          choices: "3",
          content: "D、序时账、分类账、备查账",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "567",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: "",
        }
      ],
      questionnaireId: "124",
      serialNumber: 1,
      status: true,
      title: "会计账簿按用途分为",
      type: 1,
      answer: "D",
      explain: "会计账簿按用途的不同，可分为序时账簿、分类账簿和备查账簿。",
      number:12
    },
    {
      ctime: "2020-06-08 19:45:56",
      id: "277",
      memo: "",
      must: true,
      optionDTOS: [
        {
          checked: false,
          choices: "1",
          content: "A、三栏式 ",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "565",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: ""
        },
        {
          checked: false,
          choices: "2",
          content: "B、数量金额式",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "566",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: ""
        },
        {
          checked: false,
          choices: "3",
          content: "C、多栏式",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "567",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: "",
        },
        {
          checked: false,
          choices: "3",
          content: "D、明细专栏式",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "567",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: "",
        }
      ],
      questionnaireId: "124",
      serialNumber: 2,
      status: true,
      title: "材料明细账通常采用()账簿",
      type: 1,
      answer: "B",
      explain: "数量金额式账簿适用于具有实物形态的财产物资的明细账，如：原材料明细账，库存商品等明细账。",
      number:12
    },
    {
      ctime: "2020-06-08 19:45:56",
      id: "277",
      memo: "",
      must: true,
      optionDTOS: [
        {
          checked: false,
          choices: "1",
          content: "A、三栏式、多栏式、数量金额式",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "565",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: ""
        },
        {
          checked: false,
          choices: "2",
          content: "B、日记账、分类账、备查簿",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "566",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: ""
        },
        {
          checked: false,
          choices: "3",
          content: "C、普通日记账、特种日记账、转账日记账",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "567",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: "",
        },
        {
          checked: false,
          choices: "3",
          content: "D、订本式、活页式、卡片式",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "567",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: "",
        }
      ],
      questionnaireId: "124",
      serialNumber: 3,
      status: true,
      title: "账簿按其外表形式可分为",
      type: 1,
      answer: "D",
      explain: "会计账簿按其外形特征的不同，可分为订本式账簿、活页式账簿和卡片",
      number:12
    },
    {
      ctime: "2020-06-08 19:45:56",
      id: "277",
      memo: "",
      must: true,
      optionDTOS: [
        {
          checked: false,
          choices: "1",
          content: "A、特种日记账",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "565",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: ""
        },
        {
          checked: false,
          choices: "2",
          content: "B、普通日记账",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "566",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: ""
        },
        {
          checked: false,
          choices: "3",
          content: "C、总分类账簿",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "567",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: "",
        },
        {
          checked: false,
          choices: "3",
          content: "D、明细分类账簿",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "567",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: "",
        }
      ],
      questionnaireId: "124",
      serialNumber: 4,
      status: true,
      title: "活页式账簿主要适用于",
      type: 1,
      answer: "D",
      explain: "活页式账簿主要适用于各类明细分类账。",
      number:12
    },
    {
      ctime: "2020-06-08 19:45:56",
      id: "277",
      memo: "",
      must: true,
      optionDTOS: [
        {
          checked: false,
          choices: "1",
          content: "A、复式记账",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "565",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: ""
        },
        {
          checked: false,
          choices: "2",
          content: "B、设置会计科目和账户",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "566",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: ""
        },
        {
          checked: false,
          choices: "3",
          content: "C、设置和登记账簿",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "567",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: "",
        },
        {
          checked: false,
          choices: "3",
          content: "D、编制会计分录",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "567",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: "",
        }
      ],
      questionnaireId: "124",
      serialNumber: 5,
      status: true,
      title: "下列项目中，()是连接会计凭证和会计报表的中间环节。",
      type: 1,
      answer: "C",
      explain: "会计账簿是由具有一定格式、相互联结的账页组成，以会计凭证为依据，全面、连续、系统地记录各项经济业务的簿籍。设置和登记账簿是连接会计凭证",
      number:12
    },
    {
      ctime: "2020-06-08 19:45:56",
      id: "277",
      memo: "",
      must: true,
      optionDTOS: [
        {
          checked: false,
          choices: "1",
          content: "A、采用公允价值模式进行后续计量的投资性房地产，资产负债表日公允价值高于其账面余额的差额应计人公允价值变动损益",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "565",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: ""
        },
        {
          checked: false,
          choices: "2",
          content: "B、采用公允价值模式进行后续计量的投资性房地产，不应计提折旧或摊销",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "566",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: ""
        },
        {
          checked: false,
          choices: "3",
          content: "C、已经计提减值准备的投资性房地产，其减值损失在持有期间内不得转回",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "567",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: "",
        },
        {
          checked: false,
          choices: "3",
          content: "D、采用成本模式进行后续计量的投资性房地产，按月计提的折旧或摊销应计人管理费用",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "567",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: "",
        }
      ],
      questionnaireId: "124",
      serialNumber: 6,
      status: true,
      title: "下列关于投资性房地产后续计量的表述中正确的有",
      type: 2,
      answer: ['A','B','C'
      ],
      explain: "成本模式后续计量的投资性房地产，计提折旧或者摊销应计入其他业务成本等科目，选项D不正确。",
      number:12
    },
    {
      ctime: "2020-06-08 19:45:56",
      id: "277",
      memo: "",
      must: true,
      optionDTOS: [
        {
          checked: false,
          choices: "1",
          content: "A、存货跌价准备",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "565",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: ""
        },
        {
          checked: false,
          choices: "2",
          content: "B、长期应收款坏账准备",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "566",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: ""
        },
        {
          checked: false,
          choices: "3",
          content: "C、长期股权投资减值准备",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "567",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: "",
        },
        {
          checked: false,
          choices: "3",
          content: "D、可供出售权益工具投资减值准备",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "567",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: "",
        }
      ],
      questionnaireId: "124",
      serialNumber: 7,
      status: true,
      title: "下列各项资产减值准备中，在相关资产持有期间内可以通过损益转回的有()",
      type: 2,
      answer: ['A','B'
      ],
      explain: "选项C，长期股权投资减值准备一经计提，以后会计期间不得转回;选项D，可供出售权益工具投资的减值准备可以转回，但不能通过损益转回，只能通过其他综合收益转回。",
      number:12
    },
    {
      ctime: "2020-06-08 19:45:56",
      id: "277",
      memo: "",
      must: true,
      optionDTOS: [
        {
          checked: false,
          choices: "1",
          content: "A、无论采用公允价值模式还是成本模式进行后续计量的投资性房地产，均应按照公允价值进行初始计量",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "565",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: ""
        },
        {
          checked: false,
          choices: "2",
          content: "B、外购投资性房地产的成本，包括购买价款、相关税费和可直接归属于该资产的其他支出",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "566",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: ""
        },
        {
          checked: false,
          choices: "3",
          content: "C、自行建造投资性房地产的成本，由建造该项资产达到预定可使用状态前所发生的必要支出构成",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "567",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: "",
        },
        {
          checked: false,
          choices: "3",
          content: "D、采用公允价值模式进行后续计量的投资性房地产，自行建造取得的应按照实际成本进行初始计量",
          ctime: "2020-06-08 19:45:56",
          hasOther: false,
          id: "567",
          otherContent: "",
          questionId: "277",
          status: true,
          utime: "",
        }
      ],
      questionnaireId: "124",
      serialNumber: 8,
      status: true,
      title: "投资性房地产进行初始计量时，下列处理方法中正确的有",
      type: 2,
      answer: ['B','C','D'],
      explain: "无论采用公允价值模式还是成本模式进行后续计量的投资性房地产，均应按照取得成本进行初始计量，选项A不正确。",
      number:16
    }
  ]
}

// 首页列表
exports.trainList = {
  errcode: 200,
  errmsg: "操作成功",
  data:[
    {
      id: "1252432486881878018",
      cost:true,
      applyCount: "3",
      clickCount: "18",
      consultCount: "1",
      time:'20200301-20200530',
      discountPrice:'120',
      originalPrice:'120',
      highlightLabel: "高新技能,专业知识,社会认可,启发思维,快速提升高新技能,专业知识,社会认可,启发思维,快速提升",
      pic: "https://xixiprod.oss-cn-shenzhen.aliyuncs.com/skill/image/aa02f56e-706b-4402-a7cd-1509f43b1f58.png",
      skillClassifyId: 52,
      skillName: "你的最后一堂职场PPT课程",
      sortNo: 0,
      techType: 1,
      techTypeName: "现场授课"
    },
    {
      id: "1235434523452345",
      cost:false,
      applyCount: "3",
      clickCount: "18",
      consultCount: "1",
      time:'20200301-20200530',
      discountPrice:'120',
      originalPrice:'120',
      highlightLabel: "系统导学+精讲前导+面授精讲+在线指导+习题强化+考前密训+应考经验分享",
      pic: "https://xixiprod.oss-cn-shenzhen.aliyuncs.com/skill/image/ae82a6f4-1dee-4873-a7a5-c11b587a3859.png",
      skillClassifyId: 52,
      skillName: "(免费)初级会计职称—初级会计实务",
      sortNo: 0,
      techType: 1,
      techTypeName: "网络+现场授课"
    },
  ]
}

exports.testList = {
  errcode: 200,
  errmsg: "操作成功",
  data:[
    {
      id:'23523456436234',
      applyCount: "3",
      clickCount: "18",
      consultCount: "1",
      time:'20200301-20200530',
      discountPrice:'120',
      originalPrice:'120',
      highlightLabel: "高新技能,专业知识,社会认可,启发思维,快速提升高新技能,专业知识,社会认可,启发思维,快速提升",
      id: "1252432486881878018",
      pic: "https://xixiprod.oss-cn-shenzhen.aliyuncs.com/skill/image/7ef9d524-02b7-4bf2-8023-11fac6aab758.png",
      skillClassifyId: 52,
      skillName: "2020内科规培医生春季测试",
      sortNo: 0,
      techType: 1,
      techTypeName: "现场授课"
    },
  ]
}

// 当前培训详情
exports.details = {
  errcode: 200,
  errmsg: "操作成功",
  data:{
    '1252432486881878018':{
        id: "1252432486881878018",
        cost:true,
        pic: "https://xixiprod.oss-cn-shenzhen.aliyuncs.com/skill/image/aa02f56e-706b-4402-a7cd-1509f43b1f58.png",
        skillName: "你的最后一堂职场PPT课程",
        desc:'随送电子版本教辅资料+历年真题+录播课讲义+2020学习计划【分享新学员注册解锁课程',
        highlightLabel: "高新技能,专业知识,社会认可,启发思维,快速提升高新技能,专业知识,社会认可,启发思维,快速提升",
        discountPrice:'8888',
        originalPrice:'12000',
        buyNumner: "9321",
        imgList:[
          "http://edu24ol.bs2cdn.100.com/f87fb8343b4b43f1ff0da4d3afa763f5b3f6edd9.jpg",
          "http://edu24ol.bs2cdn.100.com/5a26d757168503d7d2f003fbbcba673dd5b952f5.jpg", 
          "http://edu24ol.bs2cdn.100.com/0e8a30a0a4aedc1b399f5ad78a82c4c18e465e8a.jpg",
          "http://edu24ol.bs2cdn.100.com/e1e8ff2e336dff0070ca214d78a45844c8e5b654.jpg",
          "http://edu24ol.bs2cdn.100.com/0a17ebb8d8c69e8637ebc30fdbe32bf55aa2b924.jpg",
          "http://edu24ol.bs2cdn.100.com/5f0da7e7590a3e0607834fccc360374ce42d13bc.jpg",
          "http://edu24ol.bs2cdn.100.com/b6fa2e41581bed28113a72e84fb199dc52f77a45.jpg" 
        ]

    },
    '1235434523452345':{
        id: "1235434523452345",
        cost:false,
        pic: "https://xixiprod.oss-cn-shenzhen.aliyuncs.com/skill/image/ae82a6f4-1dee-4873-a7a5-c11b587a3859.png",
        skillName: "(免费)初级会计职称—初级会计实务",
        desc:'随送电子版本教辅资料+历年真题+录播课讲义+2020学习计划【分享新学员注册解锁课程',
        highlightLabel: "高新技能,专业知识,社会认可,启发思维,快速提升高新技能,专业知识,社会认可,启发思维,快速提升",
        discountPrice:'0',
        originalPrice:'12000',
        buyNumner: "9321",
        imgList:[
          'https://xixiprod.oss-cn-shenzhen.aliyuncs.com/skill/image/1554ad37-cd03-4c2b-8d51-78c392e2e61a.jpg',
          'https://xixiprod.oss-cn-shenzhen.aliyuncs.com/skill/image/3620a453-779c-4f7c-a356-b37d5325c0b0.jpg',
        ]
    }
  }
}

// 已购买课程
exports.buyCourse = [ ];

// 已完成测试
exports.finishTest = [];